name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  extension-ci:
    uses: steadybit/extension-kit/.github/workflows/reusable-extension-ci.yml@main
    with:
      go_version: '1.23'
      build_linux_packages: false
